services:
  qing:
    build: .
    container_name: qing-calendar
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./app:/app/app
      - ./server:/app/server
      - ./apks:/app/apks
    restart: unless-stopped
    networks:
      - default
      - icube_icube_network

networks:
  icube_icube_network:
    external: true
